# Generated by Django 6.0.5 on 2026-05-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='media/')),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
