# Generated by Django 6.0.5 on 2026-05-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='document',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='document',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterModelTable(
            name='document',
            table='document',
        ),
    ]
